name: Test

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: "Update README.md"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Update README.md
        run: |
          sed -i -E "s|Build_Latest-[0-9]{8}-blue|Build_Latest-$(date +'%Y%m%d')-blue|g" README.md
          sed -i -E "s|Amlogic_Latest-[0-9]{8}-blue|Amlogic_Latest-$(date +'%Y%m%d')-blue|g" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add README.md
          git commit -m "Auto Update $(date +'%Y-%m-%d %H:%M:%S')"
          git push
